Update endpoints archetypes with new tooling
GoogleCloudPlatform/appengine-maven-archetypes-java pull request #54
Opened 2017-01-18 22:28 UTC by frankyn

* Added Endpoints Frameworks v2.0 support
* Added gradle build support to generated archetype (this is not gradle archetype generation)
* Added support for new AppEngine plugins 
* Added comments on how to use Endpoints Frameworks v1.0 support. It's commented unless developer wants to use this framework. 
* Updated README.md to reflect changes with new tooling
* Fixed bug where archetype variables weren't replaced when archetype is generated in certain files.
* Updated archetype version to 2.0.0-0 following maven convention. 
* Added Jenkins End-2-End testing for hello-endpoints-archetype

2017-01-20 20:47 UTC, lesv requested changes
Remove Copyright notices in generated code.
Not sure where app.id is used.  Shouldn't be required anymore.

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/pom.xml
> +  <version>2.0.0-0</version>
Let's loose the `-0`

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
>          <include>nbactions.xml</include>
It might make sense to loose nbactions.xml

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/archetype-resources/pom.xml
> +<!--
We don't put a copyright here --- it's user generated code.

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/archetype-resources/pom.xml
>                  <groupId>org.apache.maven.plugins</groupId>
Not required

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/archetype-resources/pom.xml
> +                <groupId>org.apache.maven.plugins</groupId>
Not required.

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/archetype-resources/pom.xml
> +                <version>${maven.war.version}</version>
Probably not required

2017-01-20 20:47 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/web.xml
> +
No copyright in generated code.

2017-01-20 20:47 UTC, lesv commented on hello-endpoints-archetype/src/main/resources/archetype-resources/build.gradle
> +// Copyright 2017 Google Inc. All Rights Reserved.
No copyright required here.

2017-01-20 20:47 UTC, lesv commented on hello-endpoints-archetype/src/main/resources/archetype-resources/eclipse-launch-profiles/DevAppServer.launch
>  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
We may wish to get rid of these.

2017-01-20 20:47 UTC, lesv commented on hello-endpoints-archetype/src/main/resources/archetype-resources/pom.xml
> +<!--
remove copyright here.

2017-01-20 20:47 UTC, lesv commented on hello-endpoints-archetype/src/main/resources/archetype-resources/pom.xml
> +    <groupId>com.example.helloendpoints</groupId>
This should be generated by user input.

2017-01-20 20:47 UTC, lesv commented on hello-endpoints-archetype/src/main/resources/archetype-resources/pom.xml
> +    <artifactId>helloendpoints</artifactId>
This should be a `${...}`  (ie the user sets it.)

2017-01-20 20:47 UTC, lesv commented on hello-endpoints-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/web.xml
> +Copyright 2017 Google Inc. All Rights Reserved.
Remove Copyright notice.

2017-01-31 01:22 UTC, frankyn commented
@lesv PTAL

1. Acknowledging comments.
2. Adding a test to verify specific deployed version versus a prior deployment. 
3. Updated static pom values
```
<groupId>com.example.helloendpoints</groupId>
<artifactId>helloendpoints</artifactId>
```
4. Updated Copyrights to be Velocity comments
5. Updated README.md to reflect our conversation. 
6. Added e2e test to Jenkins

2017-01-31 02:27 UTC, lesv commented on endpoints-skeleton-archetype/src/main/resources/archetype-resources/build.gradle
> +    classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:${endpoints-p}'
Wow - does that really work?

2017-01-31 02:30 UTC, lesv commented
So the same comments I gave about the sample should apply here, except, of course, the parent pom doesn't appear in the generated code.  (Nor do we have copyrights).

2017-01-31 18:50 UTC, frankyn commented
@Les, I modified archetypes to use velocity comments as suggested from a prior meeting. Do you want to remove copyright headers from the archetypes?

2017-01-31 22:47 UTC, frankyn commented
@lesv PTAL

2017-02-01 01:27 UTC, lesv approved these changes

2017-02-01 01:28 UTC, merged